import test from 'node:test';import assert from 'node:assert/strict';
import {sharePages,personalSections,ellipsisText,outputShareFiles,localTimestamp,SHARE_SIZE,SHARE_LAYOUT,renderSharePng} from './settlementShare.js';
const rows=n=>Array.from({length:n},(_,i)=>({name:'Member'+i,amount:100}));
test('8 rows hard ceiling, repeated title, fixed page height',()=>{const pages=sharePages([{title:'A',summary:'還要收',label:'尚待付款',rows:rows(19)}]);assert.equal(pages.length,3);assert.deepEqual(pages.map(p=>p.rowCount),[8,8,3]);assert.ok(pages.every(p=>p.height<=SHARE_LAYOUT.safeHeight&&p.blocks[0].title==='A'));});
test('multiple receiver headers cause early pagination',()=>{const pages=sharePages(['A','B','C'].map(title=>({title,summary:'還要收',label:'尚待付款',rows:rows(2)})));assert.ok(pages.length>=2);assert.ok(pages.every(p=>p.rowCount<=8&&p.height<=SHARE_LAYOUT.safeHeight));});
test('pending is separate from unpaid, confirmed excluded, personal/other share same model',()=>{const finance={transfers:[{fromUid:'a',toUid:'b',amount:200}],projectedBalances:{a:-200,b:200}};const repayments=[{fromUid:'a',toUid:'b',amount:300,status:'pending'},{fromUid:'a',toUid:'b',amount:50,status:'confirmed'}];const sections=personalSections('a',finance,repayments,id=>id);assert.deepEqual(sections.map(s=>s.label),['已付款・待確認','尚需支付']);assert.equal(sections[0].summary,'還要付 NT$200');assert.equal(sections[0].rows[0].name,'b');});
test('rendered width ellipsis preserves complete graphemes',()=>{assert.equal(ellipsisText('long name',5,s=>s.length),'long…');assert.equal(ellipsisText('短',10,s=>s.length),'短');assert.match(localTimestamp(new Date(2026,9,1,8,3)),/2026.10.01 08:03/);});
test('native multi-file unsupported downloads only selected files; native cancel never downloads',async()=>{const files=[{name:'selected.png'}],downloaded=[];assert.equal(await outputShareFiles(files,{navigator:{canShare:()=>false},download:f=>downloaded.push(f)}),'downloaded');assert.deepEqual(downloaded,files);let called=0;await outputShareFiles(files,{navigator:{canShare:()=>true,share:async()=>{called++;}},download:()=>assert.fail()});assert.equal(called,1);assert.equal(await outputShareFiles(files,{navigator:{canShare:()=>true,share:async()=>{throw Object.assign(new Error(),{name:'AbortError'});}},download:()=>assert.fail()}),'cancelled');});
test('PNG export is 1500×2100, main amount strongest, row amounts right aligned',async()=>{const original=globalThis.document,drawn=[];const ctx={fillRect(){},beginPath(){},roundRect(){},fill(){},stroke(){},moveTo(){},lineTo(){},save(){},restore(){},translate(){},scale(){},ellipse(){},arc(){},measureText:value=>({width:value.length*30}),fillText(value,x,y){drawn.push({value,font:this.font,align:this.textAlign});}};const canvas={getContext:()=>ctx,toBlob:callback=>callback(new Blob(['PNG']))};globalThis.document={fonts:{ready:Promise.resolve()},createElement:()=>canvas};try{await renderSharePng(sharePages([{title:'A',summary:'還要收 NT$1,000',label:'尚待付款',rows:[{name:'B',amount:1000}]}])[0],{groupName:'Group',activityName:'Trip',date:new Date(),pageNumber:1,pageCount:1});assert.deepEqual([canvas.width,canvas.height],[1500,2100]);assert.deepEqual(SHARE_SIZE,{width:1500,height:2100});assert.ok(drawn.some(row=>row.value==='NT$1,000'&&row.font==='700 86px sans-serif'));assert.ok(drawn.some(row=>row.value==='NT$1,000'&&row.align==='right'));}finally{globalThis.document=original;}});
